# Generated by Django 4.2.27 on 2026-02-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='agent_text',
            new_name='image_prompt',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='user_text',
            new_name='text_content',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='dify_conversation_id',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='thinking_duration',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user_audio',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user_image',
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('initial_probe', '初始询问'), ('visual_loop', '视觉互动中'), ('review', '最终回顾')], default='initial_probe', max_length=20),
        ),
        migrations.AddField(
            model_name='interaction',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='用户的解读是否通过验证'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('question', '用户提问'), ('probe_answer', '用户初始回答'), ('ai_image', 'AI生成图'), ('user_interpretation', '用户解读'), ('ai_feedback', 'AI反馈'), ('review', '最终回顾')], max_length=20),
        ),
    ]
